ports:
- port: 8097
  onOpen: open-browser

tasks:
  - init: |
      pip install --upgrade pip
      make build
      make run
    command: |
      docker exec -it pytorch bash
  - command: gp await-port 8097 && sleep 2 && gp preview "$(gp url 8097)"
# Now in docker bash you can run:
# python main.py